version: '3.8'

networks:
  coolify:
    external: true

services:
  backend:
    build: 
      context: ./backend
    container_name: finance_backend
    restart: unless-stopped
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    expose:
      - '8000'
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance-api.rule=Host(`api-finanzas.blueberrieslab.com`)"
      - "traefik.http.routers.finance-api.entrypoints=http,https"
      - "traefik.http.services.finance-api.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
    container_name: finance_frontend
    restart: unless-stopped
    expose:
      - '80'
    depends_on:
      - backend
    networks:
      - coolify

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance.rule=Host(`finance.blueberrieslab.com`)"
      - "traefik.http.routers.finance.entrypoints=http,https"
      - "traefik.http.services.finance.loadbalancer.server.port=80"
